# Вопрос 1
Конструкция
```python
if _name == 'main__': 
```

In [2]:
from script import func

In [4]:
!python script.py

1

# Вопрос 2
Что происходит, когда открываем файл
```python
infile = open('sales_data.txt', 'г').
```

In [5]:
infile = open('real_data.txt')

In [7]:
infile.readline()

'05.10.16 23:18\t1010\t20,2\n'

In [ ]:
for line in infile:

# Задача про интервалы дат
Имеется список отсортированных по возрастанию дат dates_list. А также дата date, которая лежит между минимальным и максимальным значениями из списка dates_list. Вам необходимо определить ближайшие даты в списке dates_list, которые окружают дату date.

Пример:
```python
dates_list = ['2022-01-01', '2022-01-07', '2022-02-23', '2022-03-08', '2022-05-01', '2022-05-09', '2022-06-12']
date = '2022-04-01'
```

In [9]:
dates_list = ['2022-01-01', '2022-01-07', '2022-02-23', '2022-03-08', '2022-05-01', '2022-05-09', '2022-06-12']
dates_list

['2022-01-01',
 '2022-01-07',
 '2022-02-23',
 '2022-03-08',
 '2022-05-01',
 '2022-05-09',
 '2022-06-12']

In [ ]:
01.04.2022  # 1 апреля 2022   4 января 2022

In [13]:
'logs_2022-03-31.csv' < 'logs_2022-04-01.csv'  # 2022-04-01Z19:16:30.3029823

True

In [10]:
date = '2022-04-01'  # календарный порядок совпадает с алфавитным

In [22]:
# вариант 1
i = 0

for item in dates_list[:-1]:
    if item < date < dates_list[i+1]:
        print(i, item, dates_list[i+1])
        break
    
    i += 1

3 2022-03-08 2022-05-01

In [16]:
# вариант 2

for i in range(len(dates_list)):
    print(i, dates_list[i])

0 2022-01-01
1 2022-01-07
2 2022-02-23
3 2022-03-08
4 2022-05-01
5 2022-05-09
6 2022-06-12

In [17]:
# вариант 3

for i, item in enumerate(dates_list):
    print(i, item)

0 2022-01-01
1 2022-01-07
2 2022-02-23
3 2022-03-08
4 2022-05-01
5 2022-05-09
6 2022-06-12

### Бинарный поиск

In [21]:
dates_list

['2022-01-01',
 '2022-01-07',
 '2022-02-23',
 '2022-03-08',
 '2022-05-01',
 '2022-05-09',
 '2022-06-12']

### А что будет, когда используем код на всех данных?
Алгоритмическая сложность - во сколько раз вырастет время выполнения, когда количетсво даннных вырастет в N раз?

In [23]:
for i in range(N):
    for j in range(N):
        # вычисления

SyntaxError: unexpected EOF while parsing (<ipython-input-23-f47fcd7245fd>, line 2)

O(функция от N)
- Линейный поиск O(N)
- Квадратичный поиск O(N**2)
- Бинарный поиск O(log_2(N))

In [ ]:
1024 - 2**10 --> 10 раз

In [ ]:
- 1000 - 10 шагов
- 2000 - 11 шагов
- 4000 - 12 шагов
- 8000 - 13 шагов

In [ ]:
N --> log_2(N)

# Обработка ошибок
1. Текст ошибки указывается в последней строчке
2. Все что перед ней - место, где ошибка произошла
3. Есть встроенные типы ошибок, но можно создавать и свои

Некоторые типы ошибок из документации (точнее [перевода](https://pythonworld.ru/tipy-dannyx-v-python/isklyucheniya-v-python-konstrukciya-try-except-dlya-obrabotki-isklyuchenij.html)):
- ZeroDivisionError - деление на ноль
- ImportError - не удалось импортирование модуля или его атрибута (надо установить эту библиотеку)
- IndexError - индекс не входит в диапазон элементов.
- KeyError - несуществующий ключ (в словаре, множестве или другом объекте)
- MemoryError - недостаточно памяти
- SyntaxError - синтаксическая ошибка (вы опечатались или не закрыли скобку)
- TypeError - операция применена к объекту несоответствующего типа
- ValueError - функция получает аргумент правильного типа, но некорректного значения
- Warning - предупреждение (текст на красном фоне в юпитере это предупреждение, а не ошибка)

In [ ]:
# эту строку можно перевести в число
some_num = '123'

In [ ]:
float(some_num)

In [ ]:
# а эту уже нет (по крайней мере в десятичном счислении)
ups = '123a'

In [ ]:
# ValueError - тип ошибки, далее пояснение что произошло
# ----> 1 float(ups) - в каком месте кода произошла ошибка
float(ups)

Пример ошибки внутри функции

In [24]:
def square_sum(*args):
    total_sum = 0
    for arg in args:
        total_sum += arg**2
    
    return total_sum

In [25]:
square_sum(1, 2, 3)

14

In [26]:
# пытаемся применить к операцию возведения в квадрат к строке
# ----> 1 square_sum(1, 2, '3') - в какой функции произошла ошибка
# ----> 4         total_sum += arg**2 - в какой именно строке произошла ошибка

square_sum(1, 2, '3')

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

# План-капкан
1. Прочитать что написано на последней строчке ошибки (!!!) + переводите на русский язык. Далее читаем traceback.
2. Поискать в Гугле или Яндексе.

### Обращаемся к колегам
3. (если мы на работе) Укажите какую задачу вы изначально решаете (!!!)
4. Обязательно обратите внимание:
- Понятно ли что значат переменные в вашем коде?
- Какие данные на входе?
5. Самый правильный способ помочь исправить ошибку - воспроизводимый пример.
- Вы избавляетесь от ситуаций, когда проблема в очередности выполнения ячеек.
- Ваш коллега сможет убедиться, что проблема в коде.
- Если ошибка у коллеги НЕ воспроизводится.

Что может быть:
- устаревшие версии библиотек (особенно pandas)
- протухшие пароли/ключи от БД
- версия операционной системы
- включен ли корпоративный VPN, в каком вы регионе, проверить сетевые доступы

In [27]:
dates_list = {}

In [ ]:
# очень сложные расчеты и их много

dates_list.append(another_date)

## Как сделать, чтобы цикл с расчетом не падал каждый раз

In [ ]:
try:
    # ваш код, где может произойти ошибка
    float('123a')

except:
    # код, который выполняется в случае ошибки

In [ ]:
data = ['90', '60', '90', '240tot']
total_sum = 0

for num in data:
    try:
        total_sum += float(num)

    except:
        print('Ошибка в данных: {}'.format(num))
    
print('Итого', total_sum)

Как сохранить всю информацию об ошибке?

In [ ]:
# полная версия traceback
import traceback

try:
    float('123fff')

except Exception:
    print(traceback.print_exc())
    
print('Проехали')

### Блок finally

In [ ]:
try:
    print(stats["wednesday"])
    
except IndexError:
    print("Ошибка индекса")
    
except KeyError:
    print("Ошибка ключа")
    print(1/0)
    
finally:
    print('Эта строчка будет выполнена всегда')

### Более жизненный пример

In [ ]:
DATE_FORMATS = ['%d.%m.%y %H:%M', '%d.%m.%YT %H:%M:%S', '...']

In [ ]:
def parse_date(date):
    for format_ in DATE_FORMATS:
        try:
            return datetime.strptime(date, format_)
        except:
            pass
        
    raise ValueError(f'Неизвестная дата {date}')  # вручную вызывает ошибку

In [35]:
from datetime import datetime

In [45]:
DATE_FORMATS = ['%d.%m.%y %H:%M', '%d.%m.%YT %H:%M:%S']

In [52]:
def date_parse(date):
    for format_ in DATE_FORMATS:
        try:
            return datetime.strptime(date, format_)
        except ValueError:
            pass
        
    # return datetime(1970, 1, 1)
    
    # если функция должна падать с ошибкой при невозможности распознать даты
    raise ValueError(f'Неизвестный формат даты {date}')

In [53]:
date_parse('05.10.16 23:18')

datetime.datetime(2016, 10, 5, 23, 18)

In [54]:
date_parse('09.10.2016T 21:40:00')

datetime.datetime(2016, 10, 9, 21, 40)

In [55]:
date_parse('05.10.16Z23:18')

ValueError: Неизвестный формат даты 05.10.16Z23:18

# Важные замечания про try-except
1. Не ставьте в try-except много строчек кода
2. После отработки блоков try-except проверяйте результат на адекватность

In [56]:
with open('real_data.txt', 'r') as f:
    for line in f:
        line = line.strip().split('\t')
        
        if len(line) == 3:
            print(date, user_id, value)
            date, user_id, value = line
            print(date, user_id, value)
            date = date_parse(date)

09.10.2016T 21:40:00 1036 15,6
05.10.16 23:18 1010 20,2
2016-10-05 23:18:00 1010 20,2
09.10.2016T 21:40:00 1036 15,6
2016-10-09 21:40:00 1036 15,6
01.10.16 4:57 1042 14,8
2016-10-01 04:57:00 1042 14,8
01.10.16 23:29 1042 14,4
2016-10-01 23:29:00 1042 14,4
03.10.16 20:20 1042 14
2016-10-03 20:20:00 1042 14
04.10.16 0:35 1042 20
2016-10-04 00:35:00 1042 20
04.10.16 13:46 1042 16,2
2016-10-04 13:46:00 1042 16,2
04.10.16 17:34 1042 11
2016-10-04 17:34:00 1042 11
05.10.16 15:15 1042 10800000
2016-10-05 15:15:00 1042 10800000
06.10.16 20:45 1042 22,6
2016-10-06 20:45:00 1042 22,6
07.10.16 2:54 1042 22,4
2016-10-07 02:54:00 1042 22,4
07.10.16 5:02 1042 24,4
2016-10-07 05:02:00 1042 24,4
07.10.16 6:35 1042 16,6
2016-10-07 06:35:00 1042 16,6
08.10.2016T 16:46:00 1042 8,6
2016-10-08 16:46:00 1042 8,6
07.10.16 9:59 1052 24
2016-10-07 09:59:00 1052 24
08.10.2016T 19:36:00 1052 18,8
2016-10-08 19:36:00 1052 18,8
09.10.2016T 16:27:00 1062 11,2
2016-10-09 16:27:00 1062 11,2
05.10.16 4:38 1067 19
2016-10-05 04:38:00 1067 19
04.10.16 9:56 1078 23,4
2016-10-04 09:56:00 1078 23,4
04.10.16 14:36 1085 17
2016-10-04 14:36:00 1085 17
05.10.16 16:41 1096 20,8
2016-10-05 16:41:00 1096 20,8
01.10.16 11:55 1098 15,6
2016-10-01 11:55:00 1098 15,6
07.10.16 9:06 1105 16,2
2016-10-07 09:06:00 1105 16,2
01.10.16 4:30 1108 17,8
2016-10-01 04:30:00 1108 17,8
01.10.16 18:16 1108 18,8
2016-10-01 18:16:00 1108 18,8
02.10.16 2:58 1108 20000000
2016-10-02 02:58:00 1108 20000000
02.10.16 6:01 1108 21
2016-10-02 06:01:00 1108 21
02.10.16 20:03 1108 16,6
2016-10-02 20:03:00 1108 16,6
04.10.16 2:56 1108 20
2016-10-04 02:56:00 1108 20
04.10.16 6:57 1108 19,8
2016-10-04 06:57:00 1108 19,8
06.10.16 6:46 1108 16,8
2016-10-06 06:46:00 1108 16,8
09.10.2016T 8:33:00 1108 24000000
2016-10-09 08:33:00 1108 24000000
08.10.2016T 8:02:00 1111 12
2016-10-08 08:02:00 1111 12
05.10.16 5:25 1112 10,2
2016-10-05 05:25:00 1112 10,2
09.10.2016T 0:03:00 1112 24
2016-10-09 00:03:00 1112 24
06.10.16 10:09 1113 15,8
2016-10-06 10:09:00 1113 15,8
09.10.2016T 12:09:00 1113 22
2016-10-09 12:09:00 1113 22
05.10.16 18:00 1114 17,4
2016-10-05 18:00:00 1114 17,4
06.10.16 17:58 1114 14,8
2016-10-06 17:58:00 1114 14,8
05.10.16 23:19 1116 20
2016-10-05 23:19:00 1116 20
01.10.16 23:13 1118 11,6
2016-10-01 23:13:00 1118 11,6
09.10.2016T 21:14:00 1118 20
2016-10-09 21:14:00 1118 20
05.10.16 16:30 1123 16
2016-10-05 16:30:00 1123 16
06.10.16 5:27 1123 11,2
2016-10-06 05:27:00 1123 11,2
01.10.16 17:46 1128 12,2
2016-10-01 17:46:00 1128 12,2
01.10.16 22:28 1136 21,6
2016-10-01 22:28:00 1136 21,6
03.10.16 23:03 1136 17,4
2016-10-03 23:03:00 1136 17,4
03.10.16 8:06 1140 22
2016-10-03 08:06:00 1140 22
04.10.16 10:01 1140 22
2016-10-04 10:01:00 1140 22
01.10.16 16:53 1141 16
2016-10-01 16:53:00 1141 16
05.10.16 3:31 1145 16
2016-10-05 03:31:00 1145 16
06.10.16 4:00 1145 20
2016-10-06 04:00:00 1145 20
02.10.16 8:08 1149 10
2016-10-02 08:08:00 1149 10
07.10.16 16:12 1149 21,2
2016-10-07 16:12:00 1149 21,2
08.10.2016T 6:55:00 1149 30,4
2016-10-08 06:55:00 1149 30,4
08.10.2016T 22:55:00 1149 18800000
2016-10-08 22:55:00 1149 18800000
09.10.2016T 4:10:00 1149 14
2016-10-09 04:10:00 1149 14
09.10.2016T 10:26:00 1149 22
2016-10-09 10:26:00 1149 22
09.10.2016T 22:22:00 1149 16
2016-10-09 22:22:00 1149 16
07.10.16 6:57 1150 12,6
2016-10-07 06:57:00 1150 12,6
02.10.16 12:03 1154 13,4
2016-10-02 12:03:00 1154 13,4
04.10.16 22:51 1154 13,6
2016-10-04 22:51:00 1154 13,6
04.10.16 9:28 1159 10,2
2016-10-04 09:28:00 1159 10,2
04.10.16 13:34 1159 17,4
2016-10-04 13:34:00 1159 17,4
08.10.2016T 9:43:00 1164 22,4
2016-10-08 09:43:00 1164 22,4
07.10.16 14:57 1167 11,4
2016-10-07 14:57:00 1167 11,4
07.10.16 20:25 1175 14
2016-10-07 20:25:00 1175 14
06.10.16 12:48 1181 22,4
2016-10-06 12:48:00 1181 22,4
07.10.16 9:54 1182 18
2016-10-07 09:54:00 1182 18
10.10.16 2:35 1182 17
2016-10-10 02:35:00 1182 17
04.10.16 13:49 1193 24800000
2016-10-04 13:49:00 1193 24800000
09.10.2016T 20:49:00 1193 16,6
2016-10-09 20:49:00 1193 16,6
01.10.16 5:12 1198 17,8
2016-10-01 05:12:00 1198 17,8
06.10.16 7:52 1198 9
2016-10-06 07:52:00 1198 9
06.10.16 5:15 1201 10,6
2016-10-06 05:15:00 1201 10,6
01.10.16 16:10 1207 16,6
2016-10-01 16:10:00 1207 16,6
02.10.16 1:24 1207 24,2
2016-10-02 01:24:00 1207 24,2
02.10.16 21:17 1207 20,4
2016-10-02 21:17:00 1207 20,4
03.10.16 16:08 1207 25,6
2016-10-03 16:08:00 1207 25,6
04.10.16 17:29 1207 19,8
2016-10-04 17:29:00 1207 19,8
05.10.16 1:39 1207 16,4
2016-10-05 01:39:00 1207 16,4
05.10.16 6:33 1207 16,2
2016-10-05 06:33:00 1207 16,2
05.10.16 18:57 1207 17
2016-10-05 18:57:00 1207 17
05.10.16 20:51 1207 16,8
2016-10-05 20:51:00 1207 16,8
07.10.16 8:55 1207 19,8
2016-10-07 08:55:00 1207 19,8
07.10.16 17:40 1207 15,6
2016-10-07 17:40:00 1207 15,6
08.10.2016T 23:36:00 1207 19,2
2016-10-08 23:36:00 1207 19,2
09.10.2016T 10:25:00 1207 23,2
2016-10-09 10:25:00 1207 23,2
09.10.2016T 21:04:00 1207 10,8
2016-10-09 21:04:00 1207 10,8
04.10.16 7:38 1208 24,4
2016-10-04 07:38:00 1208 24,4
09.10.2016T 14:53:00 1208 13,4
2016-10-09 14:53:00 1208 13,4
05.10.16 17:15 1209 12
2016-10-05 17:15:00 1209 12
03.10.16 6:16 1213 18,6
2016-10-03 06:16:00 1213 18,6
06.10.16 10:04 1213 16,6
2016-10-06 10:04:00 1213 16,6
01.10.16 16:52 1218 12200000
2016-10-01 16:52:00 1218 12200000
09.10.2016T 19:10:00 1218 22400000
2016-10-09 19:10:00 1218 22400000
02.10.16 8:42 1219 15,4
2016-10-02 08:42:00 1219 15,4
03.10.16 19:32 1223 17,2
2016-10-03 19:32:00 1223 17,2
06.10.16 22:11 1223 17600000
2016-10-06 22:11:00 1223 17600000
08.10.2016T 15:18:00 1224 16,4
2016-10-08 15:18:00 1224 16,4
07.10.16 18:32 1228 18,8
2016-10-07 18:32:00 1228 18,8
08.10.2016T 13:21:00 1228 17,6
2016-10-08 13:21:00 1228 17,6
03.10.16 15:47 1230 20,6
2016-10-03 15:47:00 1230 20,6
02.10.16 22:01 1236 17,4
2016-10-02 22:01:00 1236 17,4
05.10.16 5:27 1238 13,6
2016-10-05 05:27:00 1238 13,6
09.10.2016T 14:43:00 1238 17,6
2016-10-09 14:43:00 1238 17,6
04.10.16 22:25 1242 18,4
2016-10-04 22:25:00 1242 18,4
06.10.16 4:54 1243 20,4
2016-10-06 04:54:00 1243 20,4
06.10.16 14:28 1243 20
2016-10-06 14:28:00 1243 20
01.10.16 4:27 1246 17,8
2016-10-01 04:27:00 1246 17,8
01.10.16 16:30 1248 13,2
2016-10-01 16:30:00 1248 13,2
01.10.16 21:06 1248 28,8
2016-10-01 21:06:00 1248 28,8
02.10.16 7:12 1252 22
2016-10-02 07:12:00 1252 22
04.10.16 13:51 1252 15,6
2016-10-04 13:51:00 1252 15,6
01.10.16 12:36 1253 13,6
2016-10-01 12:36:00 1253 13,6
04.10.16 17:11 1253 8,6
2016-10-04 17:11:00 1253 8,6
02.10.16 16:22 1258 22
2016-10-02 16:22:00 1258 22
08.10.2016T 19:34:00 1258 20
2016-10-08 19:34:00 1258 20
02.10.16 10:36 1263 12,6
2016-10-02 10:36:00 1263 12,6
03.10.16 6:10 1263 18
2016-10-03 06:10:00 1263 18
05.10.16 2:48 1268 16,4
2016-10-05 02:48:00 1268 16,4
07.10.16 19:36 1268 16
2016-10-07 19:36:00 1268 16
02.10.16 14:12 1269 22
2016-10-02 14:12:00 1269 22
07.10.16 3:29 1270 21,8
2016-10-07 03:29:00 1270 21,8
01.10.16 8:56 1273 14,6
2016-10-01 08:56:00 1273 14,6
08.10.2016T 13:49:00 1273 22
2016-10-08 13:49:00 1273 22
07.10.16 6:00 1274 25
2016-10-07 06:00:00 1274 25
04.10.16 13:47 1278 15,6
2016-10-04 13:47:00 1278 15,6
07.10.16 6:42 1278 17,8
2016-10-07 06:42:00 1278 17,8
08.10.2016T 3:24:00 1279 14,8
2016-10-08 03:24:00 1279 14,8
03.10.16 1:03 1281 18,2
2016-10-03 01:03:00 1281 18,2
02.10.16 6:11 1283 12,6
2016-10-02 06:11:00 1283 12,6
02.10.16 19:24 1283 11,8
2016-10-02 19:24:00 1283 11,8
07.10.16 13:37 1288 16
2016-10-07 13:37:00 1288 16
08.10.2016T 19:46:00 1288 30,4
2016-10-08 19:46:00 1288 30,4
07.10.16 2:41 1291 13,4
2016-10-07 02:41:00 1291 13,4
01.10.16 17:29 1293 18,4
2016-10-01 17:29:00 1293 18,4
02.10.16 20:12 1293 20
2016-10-02 20:12:00 1293 20
02.10.16 23:36 1294 17
2016-10-02 23:36:00 1294 17
07.10.16 10:32 1296 26
2016-10-07 10:32:00 1296 26
03.10.16 20:41 1298 21
2016-10-03 20:41:00 1298 21
03.10.16 22:35 1298 19,4
2016-10-03 22:35:00 1298 19,4
05.10.16 12:19 1298 16
2016-10-05 12:19:00 1298 16
02.10.16 11:43 1300 12,8
2016-10-02 11:43:00 1300 12,8
03.10.16 23:18 1300 14
2016-10-03 23:18:00 1300 14
03.10.16 18:28 1302 21800000
2016-10-03 18:28:00 1302 21800000
02.10.16 8:06 1303 11,8
2016-10-02 08:06:00 1303 11,8
06.10.16 6:23 1303 25,8
2016-10-06 06:23:00 1303 25,8
03.10.16 10:42 1308 18
2016-10-03 10:42:00 1308 18
06.10.16 18:52 1308 10,2
2016-10-06 18:52:00 1308 10,2
06.10.16 16:16 1313 12
2016-10-06 16:16:00 1313 12
08.10.2016T 18:12:00 1313 13,8
2016-10-08 18:12:00 1313 13,8
02.10.16 14:04 1315 16,6
2016-10-02 14:04:00 1315 16,6
06.10.16 17:08 1320 18
2016-10-06 17:08:00 1320 18
09.10.2016T 2:35:00 1323 16
2016-10-09 02:35:00 1323 16
09.10.2016T 10:08:00 1323 28,6
2016-10-09 10:08:00 1323 28,6
05.10.16 7:29 1328 18,4
2016-10-05 07:29:00 1328 18,4
05.10.16 11:58 1328 18,8
2016-10-05 11:58:00 1328 18,8
03.10.16 0:36 1330 17,8
2016-10-03 00:36:00 1330 17,8
09.10.2016T 2:08:00 1331 16,8
2016-10-09 02:08:00 1331 16,8
03.10.16 2:19 1332 19,4
2016-10-03 02:19:00 1332 19,4
04.10.16 22:01 1333 20
2016-10-04 22:01:00 1333 20
08.10.2016T 3:48:00 1334 16
2016-10-08 03:48:00 1334 16
03.10.16 1:32 1343 22
2016-10-03 01:32:00 1343 22
08.10.2016T 4:34:00 1350 12800000
2016-10-08 04:34:00 1350 12800000
04.10.16 4:09 1351 20
2016-10-04 04:09:00 1351 20
06.10.16 19:09 1353 17,4
2016-10-06 19:09:00 1353 17,4
03.10.16 1:30 1354 15,6
2016-10-03 01:30:00 1354 15,6
02.10.16 23:30 1355 22
2016-10-02 23:30:00 1355 22
08.10.2016T 6:50:00 1359 14,4
2016-10-08 06:50:00 1359 14,4
02.10.16 13:33 1362 12,2
2016-10-02 13:33:00 1362 12,2
05.10.16 21:36 1363 12,2
2016-10-05 21:36:00 1363 12,2
04.10.16 22:06 1364 20
2016-10-04 22:06:00 1364 20
01.10.16 5:29 1366 13000000
2016-10-01 05:29:00 1366 13000000
07.10.16 9:40 1367 22,4
2016-10-07 09:40:00 1367 22,4
04.10.16 7:31 1371 13,6
2016-10-04 07:31:00 1371 13,6
04.10.16 1:36 1372 30,4
2016-10-04 01:36:00 1372 30,4
07.10.16 17:25 1374 12,4
2016-10-07 17:25:00 1374 12,4
05.10.16 23:06 1377 16
2016-10-05 23:06:00 1377 16
06.10.16 14:29 1380 30,4
2016-10-06 14:29:00 1380 30,4
09.10.2016T 4:55:00 1382 23,2
2016-10-09 04:55:00 1382 23,2
05.10.16 21:24 1383 20
2016-10-05 21:24:00 1383 20
05.10.16 8:14 1386 12,6
2016-10-05 08:14:00 1386 12,6
03.10.16 11:43 1387 14,6
2016-10-03 11:43:00 1387 14,6
01.10.16 6:21 1388 11,8
2016-10-01 06:21:00 1388 11,8
03.10.16 6:03 1392 20,2
2016-10-03 06:03:00 1392 20,2
06.10.16 5:34 1393 10
2016-10-06 05:34:00 1393 10
04.10.16 23:55 1394 12,8
2016-10-04 23:55:00 1394 12,8
05.10.16 5:01 1397 20,6
2016-10-05 05:01:00 1397 20,6
05.10.16 22:54 1398 18

Чем прекрасен этот файл:
1. Даты имеют разный формат: за 8 и 9 октября формат с "09.10.2016 21:40" сменился на "09.10.2016T 21:40:00" (добавилась буква T и секунды). Разработчики объяснили этот тем, что сбились настройки после обновления одной из баз данных.
2. У покупок некоторых пользователей неизвестно значение выручки, из-за чего количество столбцов в строке уменьшается на один.
3. У некоторых строк реальная сумма покупки умножена на миллион. Так иногда действительно делают, чтобы избежать дробных чисел и работать только с целыми.

Необходимо посчитать сумму выручки из третьего столбца.

# Даты

In [ ]:
# иногда импортируют так
import datetime

In [ ]:
# можно и так
import datetime as dt

In [ ]:
# у нас будет вариант покороче (но это не одно и то же)
from datetime import datetime

In [ ]:
date_string = '09.05.2018  09:00'

In [ ]:
# сейчас date_string это просто строка
type(date_string)

In [ ]:
datetime.strptime('09.05.2018 09:00', '%d.%m.%Y %H:%M')

In [ ]:
# https://docs.python.org/3/library/datetime.html

date_datetime = datetime.strptime( date_string, '%d.%m.%Y %H:%M' )
date_datetime

In [ ]:
# теперь можем работать с датами
type(date_datetime)

In [ ]:
# получить номер года и часа
date_datetime.year, date_datetime.hour

In [ ]:
# день недели
date_datetime.weekday()

In [ ]:
# сегодня
datetime.now()

### Упражнение
С помощью метода datetime.strptime переведите строку 'May 25 2017 5:00AM' в формат datetime.

### Прибавление интервала к датам

In [ ]:
from datetime import timedelta

In [ ]:
start_date = '2018-01-01'
end_date = '2018-01-07'

In [ ]:
type(start_date)

In [ ]:
start_date_datetime = datetime.strptime(start_date, '%Y-%m-%d')
start_date_datetime

In [ ]:
start_date_datetime + timedelta(days=1)

In [ ]:
start_date_datetime + timedelta(days=-7, minutes=-1)

### Перевод обратно в строку

In [ ]:
date = datetime(2018, 9, 1)
date

In [ ]:
date.strftime('%Y-%m-%d')

In [ ]:
date.strftime('%B %d %Y %I:%M%p')

In [ ]:
datetime.now().strftime('%Y-%m-01')

In [ ]:
# как получить первый день месяца

date.strftime('%Y-%m-01')

In [ ]:
start_date = '2018-01-01'
end_date = '2018-01-07'

In [ ]:
start_date, end_date

In [ ]:
start_date_dt = datetime.strptime(start_date, '%Y-%m-%d')
end_date_dt = datetime.strptime(end_date, '%Y-%m-%d')

print(start_date_dt, end_date_dt)

In [ ]:
i = 0

while i < 10:
    # ...
    i += 1
    print(i)

In [ ]:
current_dt = start_date_dt

while current_dt <= end_date_dt:
    print(current_dt.strftime('%Y-%m-%d'))
    
    current_dt += timedelta(days=1)

In [ ]:
current_dt = start_date_dt

while current_dt.strftime('%Y-%m-%d') <= end_date:
    print(current_dt.strftime('%Y-%m-%d'))
    
    current_dt += timedelta(days=1)

In [ ]:
# можно и с помощью list comprehension
[(start_date_dt + timedelta(days=x)).strftime('%Y-%m-%d') for x in range(10)]

### Нагрузка на систему по часам

In [ ]:
stats = {}

with open('logs.csv', 'r') as f:
    for line in f:
        line = line.strip()
        print(line)
        
        break
        
        # вычисления нагрузки на систему...
        
# результат
stats

In [ ]:
# а в процентном соотношении?

###  Unixtime
Количество секунд, прошедших с 1 января 1970 года по UTC

In [ ]:
import time
from datetime import date
from datetime import datetime

In [ ]:
d = date(2019, 3, 11)

unixtime = time.mktime(d.timetuple())
unixtime

In [ ]:
from datetime import datetime

In [ ]:
datetime.fromtimestamp(1552251600)

На практике все сложнее https://habr.com/ru/post/452584/